name: post_app
description: "Post App with clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #bloc for state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.2
  # Functional programming thing
  dartz: ^0.10.1
  # Value Equality
  equatable: ^2.0.7
  #Service Locator
  get_it: ^8.0.2
  #Remote Api
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.2
  #Local cache
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
